name: On new merge into master
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout master
        uses: actions/checkout@v2

      - name: Run tests and lint the code
        run: ./gradlew --no-daemon clean check

      - name: Create Github Release
        uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
